### ISSUE TITLE
Generovani testu - vyber kategorii

### ISSUE THREAD

**Issue by moucek** [medunova/ZSWI#3]
pri generovani testu se stale vybira z defaultnich sesti kategorii, zmena poctu, ani nazvu kategorii nema vliv na vyber kategorii pri generovani testu

**Comment by zobii** [comment]
Znovu jsem zkusil vygenerovat test a funguje mi správně. Pokud v okně "Exportovat do PDF" odškrnu některou z kategorií, tak otázky dané kategorie se mi testu neobjevují. Zkusil jsem generovat 5 testů a vždy 100% správně.

**Comment by Axel5688** [comment]
doplněno dynamické načítání kategorií
